# Generated by Django 5.0.6 on 2026-06-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compatibilityedge',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gasflowedge',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='negativerule',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='processedge',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='torch',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='torchpartmapping',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
