# Generated by Django 5.0.6 on 2026-06-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_torch_cost_vnd'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='cost_vnd',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
    ]
