# Generated by Django 5.0.6 on 2026-06-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_part_cost_vnd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('INSTALLATION', 'Lắp đặt'), ('REPAIR', 'Sửa chữa'), ('LOOKUP', 'Tra cứu')], db_index=True, max_length=20)),
                ('question', models.CharField(max_length=400)),
                ('answer', models.TextField()),
                ('source', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'catalog_procedure_qa',
                'ordering': ['intent', 'question'],
                'indexes': [models.Index(fields=['intent'], name='catalog_pro_intent_715b69_idx')],
            },
        ),
    ]
