# Generated by Django 5.0.6 on 2026-06-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_procedureqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
