# Generated by Django 5.0.6 on 2026-06-18 21:15

import django.db.models.deletion
import django.utils.timezone
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_opportunity_quote_quoteline_ticket_visit_lead_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('call', 'Gọi điện'), ('email', 'Email'), ('meeting', 'Gặp mặt'), ('zalo', 'Zalo'), ('other', 'Khác')], default='call', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('activity_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_activity',
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['customer', '-activity_date'], name='crm_activity_cust_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('value_vnd', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('paid_vnd', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('pending_sign', 'Chờ ký'), ('active', 'Hiệu lực'), ('expired', 'Hết hạn'), ('cancelled', 'Hủy')], db_index=True, default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='crm.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_contracts', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='crm.quote')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_contract',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'customer'], name='crm_contract_status_idx'), models.Index(fields=['owner', '-created_at'], name='crm_contract_owner_idx')],
            },
        ),
    ]
