# Generated by Django 5.0.6 on 2026-06-21 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_quote_l1_approved_at_quote_l1_approved_by_and_more'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='recap_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.fileobject'),
        ),
        migrations.AddField(
            model_name='activity',
            name='recap_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.fileobject'),
        ),
        migrations.AddField(
            model_name='visit',
            name='recap_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.fileobject'),
        ),
        migrations.AddField(
            model_name='visit',
            name='recap_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.fileobject'),
        ),
    ]
