# Generated by Django 5.0.6 on 2026-06-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_activity_recap_file_activity_recap_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit_vnd',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
