# Generated by Django 5.0.6 on 2026-06-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_lead_campaign_alter_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='referred_by',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
