# Generated by Django 5.0.6 on 2026-06-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_lead_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('sent', 'Đã gửi'), ('pending_ceo', 'Chờ CEO duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('converted', 'Đã chuyển hợp đồng'), ('expired', 'Hết hạn')], db_index=True, default='draft', max_length=20),
        ),
    ]
