# Generated by Django 5.0.6 on 2026-06-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_contract_approved_by_contract_l1_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quote',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
