# Generated by Django 5.0.6 on 2026-06-26 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_procedureqa'),
        ('crm', '0013_ticket_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='interest_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.part'),
        ),
        migrations.AddField(
            model_name='lead',
            name='interest_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
