# Generated by Django 5.0.6 on 2026-06-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_lead_interest_part_lead_interest_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='payment_terms_note',
            field=models.TextField(blank=True),
        ),
    ]
