# Generated by Django 5.0.6 on 2026-06-27 12:10

from django.db import migrations, models


# Mức chiết khấu mặc định theo phân khúc (công ty chỉnh lại sau qua trang Bảng giá).
DEFAULTS = [
    ('dealer',     15, 'Đại lý / NPP'),
    ('factory',    10, 'Nhà máy SX'),
    ('integrator', 10, 'Robot Integrator'),
    ('oem',        12, 'OEM'),
    ('shipyard',    8, 'Đóng tàu'),
    ('other',       0, 'Khác (giá niêm yết)'),
]


def seed_tiers(apps, schema_editor):
    PriceTier = apps.get_model('crm', 'PriceTier')
    for seg, disc, label in DEFAULTS:
        PriceTier.objects.get_or_create(segment=seg, defaults={'discount_pct': disc, 'label': label})


def unseed(apps, schema_editor):
    apps.get_model('crm', 'PriceTier').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_quote_payment_terms_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(choices=[('factory', 'Nhà máy SX'), ('integrator', 'Robot Integrator'), ('dealer', 'Đại lý'), ('oem', 'OEM'), ('shipyard', 'Đóng tàu'), ('other', 'Khác')], max_length=20, unique=True)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('label', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'db_table': 'crm_price_tier',
                'ordering': ['segment'],
            },
        ),
        migrations.RunPython(seed_tiers, unseed),
    ]
