# Generated by Django 5.0.6 on 2026-07-14 16:38

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_pricetier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConversation',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('channel', models.CharField(db_index=True, default='web', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('open', 'Đang mở'), ('needs_human', 'Cần người'), ('closed', 'Đã đóng')], db_index=True, default='open', max_length=16)),
                ('flagged', models.BooleanField(db_index=True, default=False)),
                ('message_count', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_conversations', to='crm.lead')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_conversations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_bot_conversation',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Khách'), ('bot', 'Bot'), ('agent', 'Nhân viên')], max_length=8)),
                ('text', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.botconversation')),
            ],
            options={
                'db_table': 'crm_bot_message',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='botconversation',
            index=models.Index(fields=['status', '-last_message_at'], name='crm_botconv_status_idx'),
        ),
    ]
