# Generated by Django 5.0.6 on 2026-07-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_botconversation_botmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconversation',
            name='unread',
            field=models.IntegerField(default=0),
        ),
    ]
