# Generated by Django 5.0.6 on 2026-07-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_botconversation_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='lost_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('price', 'Giá cao'), ('competitor', 'Chọn đối thủ'), ('budget', 'Hết ngân sách / hoãn dự án'), ('no_need', 'Hết nhu cầu'), ('no_contact', 'Mất liên lạc'), ('other', 'Khác')], default='', max_length=20),
        ),
    ]
