# Generated by Django 5.0.6 on 2026-06-17 04:09

import apps.common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack', models.CharField(max_length=10)),
                ('bin_code', models.CharField(max_length=10)),
                ('full_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wms_bin',
                'ordering': ['full_code'],
            },
        ),
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('eta', models.DateField(blank=True, null=True)),
                ('is_arrived', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wms_asn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundOrder',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã xác nhận'), ('putaway', 'Đã cất kho'), ('cancelled', 'Hủy')], db_index=True, default='draft', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_orders', to='wms.asn')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wms_inbound_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_expected', models.IntegerField()),
                ('qty_received', models.IntegerField(default=0)),
                ('lot_no', models.CharField(blank=True, max_length=40)),
                ('order_idx', models.IntegerField(default=0)),
                ('part', models.ForeignKey(blank=True, db_column='part_no', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.part')),
                ('target_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.bin')),
                ('torch', models.ForeignKey(blank=True, db_column='torch_model', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.torch')),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms.inboundorder')),
            ],
            options={
                'db_table': 'wms_inbound_line',
                'ordering': ['order_idx'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_on_hand', models.IntegerField(default=0)),
                ('qty_reserved', models.IntegerField(default=0)),
                ('min_level', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='wms.bin')),
                ('part', models.ForeignKey(blank=True, db_column='part_no', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='catalog.part')),
                ('torch', models.ForeignKey(blank=True, db_column='torch_model', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='catalog.torch')),
            ],
            options={
                'db_table': 'wms_inventory_item',
                'ordering': ['bin__full_code'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(db_index=True, max_length=40, unique=True)),
                ('qty_remaining', models.IntegerField()),
                ('received_date', models.DateField()),
                ('expires_at', models.DateField(blank=True, db_index=True, null=True)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.bin')),
                ('part', models.ForeignKey(db_column='part_no', on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='catalog.part')),
            ],
            options={
                'db_table': 'wms_lot',
                'ordering': ['expires_at', 'received_date'],
            },
        ),
        migrations.CreateModel(
            name='OutboundOrder',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('sales_order_code', models.CharField(blank=True, max_length=20)),
                ('rule', models.CharField(choices=[('FIFO', 'Nhập trước xuất trước'), ('FEFO', 'Hết hạn trước xuất trước'), ('NEAREST', 'Gần cửa xuất nhất')], default='FIFO', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('picking', 'Đang soạn'), ('picked', 'Đã soạn xong'), ('shipped', 'Đã giao'), ('cancelled', 'Hủy')], db_index=True, default='draft', max_length=20)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbounds', to='crm.customer')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wms_outbound_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_ordered', models.IntegerField()),
                ('qty_picked', models.IntegerField(default=0)),
                ('order_idx', models.IntegerField(default=0)),
                ('part', models.ForeignKey(blank=True, db_column='part_no', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.part')),
                ('torch', models.ForeignKey(blank=True, db_column='torch_model', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.torch')),
                ('outbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms.outboundorder')),
            ],
            options={
                'db_table': 'wms_outbound_line',
                'ordering': ['order_idx'],
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('serial', models.CharField(db_index=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('in_stock', 'Trong kho'), ('reserved', 'Đã giữ'), ('shipped', 'Đã giao'), ('sold', 'Đã bán'), ('returned', 'Trả lại'), ('scrapped', 'Hủy')], db_index=True, default='in_stock', max_length=20)),
                ('sold_order', models.CharField(blank=True, max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('warranty_until', models.DateField(blank=True, null=True)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='wms.bin')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sold_to_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_serials', to='crm.customer')),
                ('torch', models.ForeignKey(db_column='torch_model', on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='catalog.torch')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wms_serial',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('is_picked', models.BooleanField(default=False)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.bin')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.lot')),
                ('outbound_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='wms.outboundline')),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.serialnumber')),
            ],
            options={
                'db_table': 'wms_pick_list_item',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wms_warehouse',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('inbound', 'Nhập kho'), ('outbound', 'Xuất kho'), ('adjust', 'Điều chỉnh'), ('transfer', 'Chuyển kho'), ('return', 'Trả hàng')], db_index=True, max_length=20)),
                ('ref_kind', models.CharField(blank=True, max_length=20)),
                ('ref_id', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.bin')),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(blank=True, db_column='part_no', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.part')),
                ('torch', models.ForeignKey(blank=True, db_column='torch_model', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.torch')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='wms.warehouse')),
            ],
            options={
                'db_table': 'wms_stock_movement',
                'ordering': ['-ts'],
            },
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbounds', to='wms.warehouse'),
        ),
        migrations.AddField(
            model_name='inboundorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbounds', to='wms.warehouse'),
        ),
        migrations.AddField(
            model_name='asn',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asns', to='wms.warehouse'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='wms.warehouse')),
            ],
            options={
                'db_table': 'wms_zone',
                'ordering': ['warehouse', 'code'],
            },
        ),
        migrations.AddField(
            model_name='bin',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='wms.zone'),
        ),
        migrations.AddConstraint(
            model_name='inboundline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('part__isnull', False), ('torch__isnull', True)), models.Q(('part__isnull', True), ('torch__isnull', False)), _connector='OR'), name='inbound_part_xor_torch'),
        ),
        migrations.AddConstraint(
            model_name='inboundline',
            constraint=models.CheckConstraint(check=models.Q(('qty_received__lte', models.F('qty_expected'))), name='inbound_received_le_expected'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['part'], name='inv_part_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['torch'], name='inv_torch_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('part__isnull', False)), fields=('bin', 'part'), name='uniq_bin_part'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('torch__isnull', False)), fields=('bin', 'torch'), name='uniq_bin_torch'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('part__isnull', False), ('torch__isnull', True)), models.Q(('part__isnull', True), ('torch__isnull', False)), _connector='OR'), name='inv_part_xor_torch'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(check=models.Q(('qty_on_hand__gte', 0)), name='inv_qty_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(check=models.Q(('qty_reserved__gte', 0)), name='inv_reserved_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(check=models.Q(('qty_reserved__lte', models.F('qty_on_hand'))), name='inv_reserved_le_onhand'),
        ),
        migrations.AddConstraint(
            model_name='outboundline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('part__isnull', False), ('torch__isnull', True)), models.Q(('part__isnull', True), ('torch__isnull', False)), _connector='OR'), name='outbound_part_xor_torch'),
        ),
        migrations.AddConstraint(
            model_name='outboundline',
            constraint=models.CheckConstraint(check=models.Q(('qty_picked__lte', models.F('qty_ordered'))), name='outbound_picked_le_ordered'),
        ),
        migrations.AddIndex(
            model_name='serialnumber',
            index=models.Index(fields=['status', 'torch'], name='wms_serial_status_182aed_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['part', '-ts'], name='mov_part_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['bin', '-ts'], name='mov_bin_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', '-ts'], name='mov_wh_idx'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='uniq_zone_per_wh'),
        ),
        migrations.AddConstraint(
            model_name='bin',
            constraint=models.UniqueConstraint(fields=('zone', 'rack', 'bin_code'), name='uniq_bin_in_zone'),
        ),
    ]
