# Generated by Django 5.0.6 on 2026-06-22 08:46

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_compatibilityedge_source_and_more'),
        ('wms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('open', 'Đang đếm'), ('applied', 'Đã áp dụng'), ('cancelled', 'Hủy')], db_index=True, default='open', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_counts', to='wms.warehouse')),
            ],
            options={
                'db_table': 'wms_cycle_count',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CycleCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.IntegerField(default=0)),
                ('counted_qty', models.IntegerField(default=0)),
                ('counted_at', models.DateTimeField(auto_now=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.bin')),
                ('part', models.ForeignKey(blank=True, db_column='part_no', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.part')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms.cyclecount')),
                ('torch', models.ForeignKey(blank=True, db_column='torch_model', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.torch')),
            ],
            options={
                'db_table': 'wms_cycle_count_line',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cyclecountline',
            constraint=models.UniqueConstraint(fields=('session', 'bin', 'part', 'torch'), name='uniq_cc_line'),
        ),
    ]
