# Generated by Django 5.0.6 on 2026-06-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_cyclecount_cyclecountline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundline',
            name='lot_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='received_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
