# Generated by Django 5.0.6 on 2026-06-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_inboundline_lot_expires_inventoryitem_received_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('picking', 'Đang soạn'), ('picked', 'Đã soạn xong'), ('partial', 'Giao một phần'), ('shipped', 'Đã giao'), ('cancelled', 'Hủy')], db_index=True, default='draft', max_length=20),
        ),
    ]
