# Generated by Django 5.0.6 on 2026-06-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0004_alter_outboundorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundline',
            name='qty_putaway',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inboundorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã xác nhận'), ('partial', 'Nhận một phần'), ('putaway', 'Đã cất kho'), ('cancelled', 'Hủy')], db_index=True, default='draft', max_length=20),
        ),
    ]
