# Generated by Django 5.0.6 on 2026-06-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_inboundline_qty_putaway_alter_inboundorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundline',
            name='serials_raw',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inboundline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='inboundorder',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='inboundorder',
            name='supplier',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
