# Generated by Django 5.0.6 on 2026-06-26 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_purchaseorder_carrier_and_more'),
        ('wms', '0006_inboundline_serials_raw_inboundline_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundorder',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_orders', to='purchasing.purchaseorder'),
        ),
    ]
