# Generated by Django 5.0.6 on 2026-06-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0007_inboundorder_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundorder',
            name='shortage_note',
            field=models.TextField(blank=True),
        ),
    ]
