# Generated by Django 5.0.6 on 2026-06-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Khách hàng'), ('sales', 'Sales'), ('warehouse', 'Nhân viên kho'), ('wh_manager', 'Quản lý kho'), ('service', 'Kỹ sư dịch vụ'), ('manager', 'Quản lý'), ('ceo', 'CEO'), ('admin', 'Admin')], db_index=True, default='sales', max_length=20),
        ),
    ]
