# Generated by Django 5.0.6 on 2026-06-17 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDeadLetter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(db_index=True, max_length=40)),
                ('payload', models.JSONField()),
                ('error', models.TextField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('retries', models.IntegerField(default=0)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'learning_eventdeadletter',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(max_length=20)),
                ('query_text', models.TextField()),
                ('planner_tools', models.JSONField(default=list)),
                ('response_text', models.TextField(blank=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('conf_tier', models.CharField(blank=True, max_length=10)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('critic_score', models.IntegerField(blank=True, db_index=True, null=True)),
                ('critic_note', models.TextField(blank=True)),
                ('promoted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'learning_querylog',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='GoldenExample',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('ideal_tools', models.JSONField(default=list)),
                ('ideal_answer', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('score', models.IntegerField()),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.querylog')),
            ],
            options={
                'db_table': 'learning_goldenexample',
                'ordering': ['-created_at'],
            },
        ),
    ]
