# Generated by Django 5.0.6 on 2026-06-17 04:09

import apps.common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(db_index=True, max_length=30)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=80)),
                ('size_bytes', models.BigIntegerField()),
                ('backend', models.CharField(default='s3', max_length=20)),
                ('bucket', models.CharField(default='tokinarc', max_length=63)),
                ('path', models.CharField(max_length=500)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('related_kind', models.CharField(blank=True, max_length=40)),
                ('related_id', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'storage_fileobject',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['related_kind', 'related_id'], name='storage_fil_related_6d2b3d_idx')],
            },
        ),
    ]
