# Generated by Django 5.0.6 on 2026-06-17 04:09

import apps.common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('order_type', models.CharField(choices=[('one_off', 'Đơn bán'), ('framework', 'Hợp đồng khung')], db_index=True, default='one_off', max_length=20)),
                ('issued_date', models.DateField()),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('total_vnd', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('paid_vnd', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('payment_terms', models.CharField(choices=[('full_on_delivery', '100% khi giao'), ('half_advance', '50% tạm ứng – 50% khi giao'), ('net_30', 'Công nợ 30 ngày'), ('net_60', 'Công nợ 60 ngày')], default='full_on_delivery', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('pending', 'Chờ ký'), ('active', 'Hiệu lực'), ('shipping', 'Đang giao'), ('completed', 'Hoàn tất'), ('cancelled', 'Hủy')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_orders', to=settings.AUTH_USER_MODEL)),
                ('parent_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_orders', to='sales.salesorder')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_salesorder',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=apps.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_vnd', models.DecimalField(decimal_places=0, max_digits=14)),
                ('paid_at', models.DateField()),
                ('method', models.CharField(choices=[('transfer', 'Chuyển khoản'), ('cash', 'Tiền mặt'), ('other', 'Khác')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.salesorder')),
            ],
            options={
                'db_table': 'sales_payment',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=14)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=0, max_digits=14)),
                ('shipped_qty', models.IntegerField(default=0)),
                ('order_idx', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
                ('part', models.ForeignKey(blank=True, db_column='part_no', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.part')),
                ('torch', models.ForeignKey(blank=True, db_column='torch_model', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.torch')),
            ],
            options={
                'db_table': 'sales_salesorderline',
                'ordering': ['order_idx'],
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer', 'status', '-issued_date'], name='sales_sales_custome_9286f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(check=models.Q(('paid_vnd__lte', models.F('total_vnd'))), name='order_paid_le_total'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(check=models.Q(('shipped_qty__lte', models.F('qty'))), name='oline_shipped_le_qty'),
        ),
    ]
