# Generated by Django 5.0.6 on 2026-06-22 13:59

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_customer_credit_limit_vnd'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateField()),
                ('subtotal_vnd', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('tax_pct', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('tax_vnd', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total_vnd', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('issued', 'Đã xuất'), ('cancelled', 'Hủy')], db_index=True, default='issued', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.salesorder')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_invoice',
                'ordering': ['-created_at'],
            },
        ),
    ]
