# Generated by Django 5.0.6 on 2026-06-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='misa_ref',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='invoice',
            name='misa_status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
