# Generated by Django 5.0.6 on 2026-06-22 14:40

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_compatibilityedge_source_and_more'),
        ('crm', '0007_customer_credit_limit_vnd'),
        ('sales', '0003_invoice_misa_ref_invoice_misa_status_and_more'),
        ('wms', '0003_inboundline_lot_expires_inventoryitem_received_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('received', 'Đã nhận lại'), ('cancelled', 'Hủy')], db_index=True, default='draft', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('total_vnd', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='crm.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='sales.salesorder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_orders', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='wms.warehouse')),
            ],
            options={
                'db_table': 'sales_return',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('order_idx', models.IntegerField(default=0)),
                ('part', models.ForeignKey(db_column='part_no', on_delete=django.db.models.deletion.PROTECT, to='catalog.part')),
                ('target_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.bin')),
                ('ro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.returnorder')),
            ],
            options={
                'db_table': 'sales_return_line',
                'ordering': ['order_idx'],
            },
        ),
    ]
