# Generated by Django 5.0.6 on 2026-06-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_returnorder_returnline'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='ship_address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
