# Generated by Django 5.0.6 on 2026-06-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesorder_ship_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='payment_terms_note',
            field=models.TextField(blank=True),
        ),
    ]
